# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Hendrick
email: b.r.hendrick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Agile Practitioner - Product Manager - Technology Ethicist
baseurl:  # the subpath of your site, e.g. /blog
url: "http://hndrck.github.io" # the base hostname & protocol for your site

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #80B3FF
  primary-rgb: 000000 #"128,179,255"
  secondary: f5f5f5 #FD6E8A
  secondary-dark: 080808 #A2122F


# Social media profiles - feel free to add more here
twitter_username: rhymeswithzion
github_username:  hndrck
facebook_username: brianhendrick
instagram_username: rhymeswithzion
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/hendrickbrian/

# Address information
address_street: Born in Toronto, Ontario, Canada
address_city: Based in London, United Kingdom


# Build settings
markdown: kramdown
